# permissions for end users to view casdoors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: casdoor-viewer-role
rules:
- apiGroups:
  - operator.casdoor.org
  resources:
  - casdoors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.casdoor.org
  resources:
  - casdoors/status
  verbs:
  - get
